/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Reportes.java
 *
 * Created on 28-ago-2013, 15:36:33
 */
package vista;

import conexion.Operaciones;
import java.awt.Dimension;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanki
 */
public class AdministracionDeUsuarios extends javax.swing.JFrame {
    private JLabel fondo=new JLabel(new ImageIcon("imagenes/fondo.jpg"));
    private Operaciones operaciones=new Operaciones();
    final int filas = 15;
    int alto;
    JScrollBar barra;
    public AdministracionDeUsuarios() {
       
        initComponents();
        iniciarPaginadorTablaPedidos();
        this.setLocationRelativeTo(null);
        comboMenu.setSelectedIndex(1);
        addFondo();
    }
    public void addFondo(){
        fondo.setBounds(0,0, 850, 650);
        add(fondo);
    }
    public void iniciarPaginadorTablaPedidos(){
        Dimension dimension = tablaUsuarios.getPreferredSize();
        jScrollPane1.setPreferredSize(new Dimension(dimension.width,
        tablaUsuarios.getRowHeight()*filas));
    }
    
  
    public void anterior(){
        alto = tablaUsuarios.getRowHeight() * (filas-1);
        barra = jScrollPane1.getVerticalScrollBar();
        barra.setValue( barra.getValue() - alto );
    }
    public void siguiente(){
        alto = tablaUsuarios.getRowHeight() * (filas - 1);
        barra = jScrollPane1.getVerticalScrollBar();
        barra.setValue( barra.getValue() + alto );
    }
    public void crearCuenta(){
        nuevoUsuario panelNuevoUsuario=new nuevoUsuario(this, rootPaneCheckingEnabled,false,""+comboMenu.getSelectedItem(),0);
        panelNuevoUsuario.setVisible(true);
        actualizar();
    }
    public void eliminarCuenta(){
        
    }
    public void editarCuenta(){
        int id=idSeleccionadoEnTabla();
        if(id!=0){
        nuevoUsuario panelNuevoUsuario=new nuevoUsuario(this, rootPaneCheckingEnabled,true,""+comboMenu.getSelectedItem(),id);
        panelNuevoUsuario.setVisible(true);
        }
        actualizar();
    }
    public void actualizar(){
        String sql="";
            if(comboMenu.getSelectedItem().equals("Usuarios del sistema")){
                sql="SELECT u.id_usuario, u.login, p.nombre, p.apellidos, p.telefono"
                + " FROM usuario u, persona p "
                + " WHERE u.persona_id = p.id";
                labelAdministrar.setText("Adminitrar Usuarios");
            }
            if(comboMenu.getSelectedItem().equals("Clientes del sistema")){
                /*sql="SELECT p.nombre, p.apellidos, p.telefono, pa.saldo"
                + " FROM persona p, pedido ped, pago pa"
                + " WHERE  ped.persona_id= p.id"
                + " AND pa.pedido_id=ped.id";*/
                sql="SELECT distinct p.id, p.nombre, p.apellidos, p.telefono from persona p, pedido ped, usuario usu where p.id<>usu.persona_id ";
                labelAdministrar.setText("Adminitrar Clientes");
            }
            operaciones.getPedidos((DefaultTableModel) tablaUsuarios.getModel(),sql);
    }
    public int idSeleccionadoEnTabla(){
        // Nuevamente obtenemos el modelo de la tabla
        int id=0;
        DefaultTableModel modelo = (DefaultTableModel) tablaUsuarios.getModel();
        //ahora obtenemos la fila selccionada
        int fila_select = tablaUsuarios.getSelectedRow();
        if(fila_select<0){
            // no se puede eliminar
            JOptionPane.showMessageDialog(this,"SSeleccione un Pedido de la tabla de Pedidos");
        }else {
             id=(Integer)modelo.getValueAt(fila_select, 0);   
        }
        return id;
     }
  
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboMenu = new javax.swing.JComboBox();
        labelRoles = new javax.swing.JLabel();
        labelAdministrar = new javax.swing.JLabel();
        crearCuenta = new javax.swing.JButton();
        eliminarCuenta = new javax.swing.JButton();
        editarCuenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        siguiente = new javax.swing.JButton();
        anterior = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        comboMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Usuarios del sistema", "Clientes del sistema" }));
        comboMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMenuActionPerformed(evt);
            }
        });
        comboMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                comboMenuKeyPressed(evt);
            }
        });

        labelRoles.setFont(new java.awt.Font("Arial", 1, 14));
        labelRoles.setText("Roles");

        labelAdministrar.setFont(new java.awt.Font("Arial", 1, 14));
        labelAdministrar.setText("Administrar Usuarios");

        crearCuenta.setText("Crear Cuenta");
        crearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaActionPerformed(evt);
            }
        });
        crearCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                crearCuentaKeyPressed(evt);
            }
        });

        eliminarCuenta.setText("Eliminar Cuenta");
        eliminarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarCuentaActionPerformed(evt);
            }
        });
        eliminarCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                eliminarCuentaKeyPressed(evt);
            }
        });

        editarCuenta.setText("Editar Cuenta");
        editarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCuentaActionPerformed(evt);
            }
        });
        editarCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editarCuentaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAdministrar))
                        .addGap(18, 18, 18)
                        .addComponent(crearCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminarCuenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarCuenta))
                    .addComponent(labelRoles))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRoles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAdministrar)
                    .addComponent(crearCuenta)
                    .addComponent(eliminarCuenta)
                    .addComponent(editarCuenta))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaUsuarios);

        siguiente.setText("Siguiente");
        siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguienteActionPerformed(evt);
            }
        });
        siguiente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                siguienteKeyPressed(evt);
            }
        });

        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });
        anterior.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                anteriorKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(anterior)
                        .addGap(10, 10, 10)
                        .addComponent(siguiente)
                        .addGap(191, 191, 191))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anterior)
                    .addComponent(siguiente))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaActionPerformed
        crearCuenta();
}//GEN-LAST:event_crearCuentaActionPerformed

    private void crearCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_crearCuentaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER)
            crearCuenta();
}//GEN-LAST:event_crearCuentaKeyPressed

    private void eliminarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarCuentaActionPerformed
        eliminarCuenta();
}//GEN-LAST:event_eliminarCuentaActionPerformed

    private void eliminarCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_eliminarCuentaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER)
            eliminarCuenta();
}//GEN-LAST:event_eliminarCuentaKeyPressed

    private void editarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCuentaActionPerformed
        editarCuenta();
}//GEN-LAST:event_editarCuentaActionPerformed

    private void editarCuentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editarCuentaKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER)
            editarCuenta();
}//GEN-LAST:event_editarCuentaKeyPressed

    private void siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguienteActionPerformed
        siguiente();
}//GEN-LAST:event_siguienteActionPerformed

    private void siguienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_siguienteKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER)
            siguiente();
}//GEN-LAST:event_siguienteKeyPressed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
        anterior();
}//GEN-LAST:event_anteriorActionPerformed

    private void anteriorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_anteriorKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER)
            anterior();
}//GEN-LAST:event_anteriorKeyPressed

    private void comboMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMenuActionPerformed
        actualizar();
    }//GEN-LAST:event_comboMenuActionPerformed

    private void comboMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_comboMenuKeyPressed
        if (evt.getKeyCode() == evt.VK_ENTER)
            actualizar();
    }//GEN-LAST:event_comboMenuKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                AdministracionDeUsuarios dialog = new AdministracionDeUsuarios();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JComboBox comboMenu;
    private javax.swing.JButton crearCuenta;
    private javax.swing.JButton editarCuenta;
    private javax.swing.JButton eliminarCuenta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAdministrar;
    private javax.swing.JLabel labelRoles;
    private javax.swing.JButton siguiente;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
