/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HistorialPagosPedido.java
 *
 * Created on 22-ago-2013, 13:47:58
 */
package vista;

import conexion.Operaciones;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import objetos.Pago;
import objetos.Pedido;
import objetos.Persona;
import objetos.Usuario;

/**
 *
 * @author juanki
 */

public class HistorialPagosPedido extends javax.swing.JDialog {
    private JLabel fondo=new JLabel(new ImageIcon("imagenes/fondo.jpg"));
    private Pago pago;
    private Pedido pedido;
    private Persona cliente;
    
    private int idPedido;
    private Operaciones operaciones;
    /** Creates new form HistorialPagosPedido */
    public HistorialPagosPedido(java.awt.Frame parent, boolean modal,int idPedido,Operaciones operaciones) {
        super(parent, modal);
        this.idPedido=idPedido;
        this.operaciones=operaciones;
        this.setLocationRelativeTo(null);
        initComponents();
        inciarValoresDefecto();
        addFondo();
    }
    public void addFondo(){
        fondo.setBounds(0,0, 500, 500);
        add(fondo);
    }
    private void inciarValoresDefecto(){
        recuperarDatos();
        llenarTabla();
        llenarDatosLabels();
    }
    public void recuperarDatos(){
        pago=new Pago(idPedido);
        pedido =new Pedido(idPedido);
        cliente=new Persona(pedido.getIdCliente());
        
    }
    public void llenarDatosLabels(){
        clienteLabel.setText("Cliente : "+cliente.getApellido()+" "+cliente.getName());
        idPedidoLabel.setText("ID Pedido :"+pedido.getId());
        costoLente.setText("Costo Lente :"+pago.getCostoLente());
        costoMontura.setText("Costo Montura :"+pago.getCostoArmazon());
        costoVarios.setText("Costo Varios :"+pago.getCostoConsulta());
        descuento.setText("Descuento :"+pago.getDescuento());
        totalAPagar.setText("Total a Pagar :"+(pago.getMontoTotal()-pago.getDescuento()));
        totalACuenta.setText("Total a Cuenta :"+(pago.getMontoTotal()-pago.getDescuento()-pago.getSaldo()));
        saldoActual.setText("Saldo Actual :"+pago.getSaldo());
    }
    public void llenarTabla(){
        String sql = "SELECT a.a_cuenta, a.fecha_deposito, usu.login"
                   + " FROM a_cuenta a, usuario usu"
                   + " WHERE pago_id ="+pago.getId();
                   
        operaciones.getPedidos((DefaultTableModel) tablaHistoriaDePagos.getModel(),sql);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tablaHistoriaDePagos = new javax.swing.JTable();
        clienteLabel = new javax.swing.JLabel();
        idPedidoLabel = new javax.swing.JLabel();
        saldoActual = new javax.swing.JLabel();
        totalACuenta = new javax.swing.JLabel();
        costoLente = new javax.swing.JLabel();
        costoMontura = new javax.swing.JLabel();
        costoGafaDeSol = new javax.swing.JLabel();
        costoVarios = new javax.swing.JLabel();
        totalAPagar = new javax.swing.JLabel();
        descuento = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaHistoriaDePagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaHistoriaDePagos.setFocusable(false);
        jScrollPane2.setViewportView(tablaHistoriaDePagos);

        clienteLabel.setText("Cliente :");

        idPedidoLabel.setText("ID Pedido :");

        saldoActual.setText("Saldo Acual :");

        totalACuenta.setText("Total Acuenta :");

        costoLente.setText("Costo Lente :");

        costoMontura.setText("Costo Montura");

        costoGafaDeSol.setText("Costo Gafa de Sol :");

        costoVarios.setText("Costo Varios :");

        totalAPagar.setText("Total a Pagar :");

        descuento.setText("Descuento :");

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("Lista de pagos a cuenta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(clienteLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(idPedidoLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(costoLente)
                        .addGap(92, 92, 92)
                        .addComponent(costoGafaDeSol))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(costoVarios)
                        .addGap(90, 90, 90)
                        .addComponent(costoMontura))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalACuenta)
                            .addComponent(saldoActual)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(aceptar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(descuento)
                                .addGap(99, 99, 99)
                                .addComponent(totalAPagar))
                            .addComponent(jLabel1))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(clienteLabel)
                .addGap(6, 6, 6)
                .addComponent(idPedidoLabel)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costoLente)
                    .addComponent(costoGafaDeSol))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(costoVarios)
                    .addComponent(costoMontura))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descuento)
                    .addComponent(totalAPagar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(totalACuenta)
                .addGap(6, 6, 6)
                .addComponent(saldoActual)
                .addGap(18, 18, 18)
                .addComponent(aceptar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        dispose();
    }//GEN-LAST:event_aceptarActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel clienteLabel;
    private javax.swing.JLabel costoGafaDeSol;
    private javax.swing.JLabel costoLente;
    private javax.swing.JLabel costoMontura;
    private javax.swing.JLabel costoVarios;
    private javax.swing.JLabel descuento;
    private javax.swing.JLabel idPedidoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel saldoActual;
    private javax.swing.JTable tablaHistoriaDePagos;
    private javax.swing.JLabel totalACuenta;
    private javax.swing.JLabel totalAPagar;
    // End of variables declaration//GEN-END:variables
}
