/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pedido.java
 *
 * Created on 10-jul-2013, 8:06:50
 */
package vista;

import java.sql.Time;
import java.util.Date;
import objetos.Lente;
import objetos.Montura;
import objetos.Pago;
import objetos.Pedido;
import objetos.Persona;
import objetos.Usuario;
/**
 *
 * @author juanki
 */
public class pedido extends javax.swing.JPanel {

    /** Creates new form pedido */
    Time hora=new Time(0, 0, 0);
    public pedido() {
        initComponents();
        System.out.println(getSize().height+" "+getSize().width);
        valoresPorDefecto();
        //setLayout(null);
    }
    public void valoresPorDefecto(){
        //fechas
        Date fechaActual=new Date();
        fecha_ingreso.setDate(fechaActual);
        fecha_ingreso.setMinSelectableDate(fechaActual);
        fecha_entrega.setMinSelectableDate(fechaActual);
        
        //Costos $$
        lente.setText("0");
        armazon.setText("0");
        consulta.setText("0");
        descuento.setText("0");
        a_cuenta.setText("0");
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        apellido_cliente = new javax.swing.JTextField();
        a_cuenta = new javax.swing.JTextField();
        saldo = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        total_a_pagar = new javax.swing.JTextField();
        nombre_cliente = new javax.swing.JTextField();
        doctor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        audicion = new javax.swing.JTextField();
        altura = new javax.swing.JTextField();
        d_p_lejos = new javax.swing.JTextField();
        d_p_cerca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        marca_montura = new javax.swing.JTextField();
        tamanio_montura = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        codigo_montura = new javax.swing.JTextField();
        color_montura = new javax.swing.JTextField();
        tipo_montura = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        material_lente = new javax.swing.JTextField();
        tipo_lente = new javax.swing.JTextField();
        color_lente = new javax.swing.JTextField();
        vision_lente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lente = new javax.swing.JTextField();
        armazon = new javax.swing.JTextField();
        consulta = new javax.swing.JTextField();
        total_2 = new javax.swing.JTextField();
        descuento = new javax.swing.JTextField();
        fecha_ingreso = new com.toedter.calendar.JDateChooser();
        fecha_entrega = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lDEsferico = new javax.swing.JTextField();
        lIEsferico = new javax.swing.JTextField();
        lICilindrico = new javax.swing.JTextField();
        lIEje = new javax.swing.JTextField();
        lDEje = new javax.swing.JTextField();
        lDCilindrico = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cercaLejos = new javax.swing.JComboBox();
        cDEsferico = new javax.swing.JTextField();
        cIEsferico = new javax.swing.JTextField();
        cICilindrico = new javax.swing.JTextField();
        cIEje = new javax.swing.JTextField();
        cDCilindrico = new javax.swing.JTextField();
        cDEje = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        l_dos_puntos = new javax.swing.JLabel();
        minuto_ini = new javax.swing.JComboBox();
        hora_ini = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        jLabel2.setText("Apellidos");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, -1));

        jLabel3.setText("Telefono");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        jLabel4.setText("Total");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, -1, -1));

        jLabel5.setText("Acuenta");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        jLabel6.setText("Saldo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, -1, -1));

        jLabel7.setText("Doctor");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));
        add(apellido_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 237, -1));

        a_cuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                a_cuentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_cuentaKeyTyped(evt);
            }
        });
        add(a_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 70, -1));

        saldo.setEditable(false);
        saldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                saldoKeyTyped(evt);
            }
        });
        add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 70, -1));

        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 85, -1));

        total_a_pagar.setEditable(false);
        total_a_pagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                total_a_pagarKeyTyped(evt);
            }
        });
        add(total_a_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 70, -1));
        add(nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 234, -1));
        add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 241, -1));

        jLabel8.setText("AUDICION");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, -1, -1));

        jLabel9.setText("ALTURA");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, -1, -1));

        jLabel10.setText("D. P. LEJOS");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 450, -1, -1));

        jLabel11.setText("D. P. CERCA");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 450, -1, -1));
        add(audicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 60, -1));
        add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 62, -1));
        add(d_p_lejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 56, -1));
        add(d_p_cerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 470, 61, -1));

        jLabel12.setText("Oservaciones");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 500, -1, -1));

        observaciones.setColumns(20);
        observaciones.setRows(5);
        jScrollPane1.setViewportView(observaciones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 500, 268, 68));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setText("Marca");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 46, -1, -1));

        jLabel30.setText("Codigo");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 72, -1, -1));

        jLabel31.setText("Color");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 98, -1, -1));

        jLabel32.setText("Tipo");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 124, -1, -1));

        jLabel33.setText("Tamaño");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 150, -1, -1));
        jPanel1.add(marca_montura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 43, 79, -1));

        tamanio_montura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tamanio_monturaActionPerformed(evt);
            }
        });
        jPanel1.add(tamanio_montura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 147, 79, -1));

        jLabel34.setText("MONTURA/ARMAZON");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));
        jPanel1.add(codigo_montura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 69, 79, -1));
        jPanel1.add(color_montura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 95, 79, -1));
        jPanel1.add(tipo_montura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 121, 79, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, 180));

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("LENTE");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jLabel14.setText("Material");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 36, -1, -1));

        jLabel15.setText("Tipo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 65, -1, -1));

        jLabel16.setText("Color");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 87, -1, -1));

        jLabel17.setText("Vision");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 116, -1, -1));

        material_lente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                material_lenteActionPerformed(evt);
            }
        });
        jPanel2.add(material_lente, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 36, 73, -1));

        tipo_lente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipo_lenteActionPerformed(evt);
            }
        });
        jPanel2.add(tipo_lente, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 62, 73, -1));

        color_lente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color_lenteActionPerformed(evt);
            }
        });
        jPanel2.add(color_lente, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 87, 73, -1));

        vision_lente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vision_lenteActionPerformed(evt);
            }
        });
        jPanel2.add(vision_lente, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 113, 73, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 210, 150));

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Lente");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel19.setText("Armazon");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel20.setText("Consulta");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 21));

        jLabel21.setText("Total");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel22.setText("Descuento");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lenteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lenteKeyTyped(evt);
            }
        });
        jPanel3.add(lente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 71, -1));

        armazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                armazonActionPerformed(evt);
            }
        });
        armazon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                armazonKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                armazonKeyTyped(evt);
            }
        });
        jPanel3.add(armazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 71, -1));

        consulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                consultaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                consultaKeyTyped(evt);
            }
        });
        jPanel3.add(consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 71, -1));

        total_2.setEditable(false);
        total_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                total_2KeyTyped(evt);
            }
        });
        jPanel3.add(total_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 71, -1));

        descuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descuentoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descuentoKeyTyped(evt);
            }
        });
        jPanel3.add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 72, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 56, 210, 159));

        fecha_ingreso.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fecha_ingresoAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        fecha_ingreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fecha_ingresoKeyTyped(evt);
            }
        });
        add(fecha_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 31, -1, -1));
        add(fecha_entrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(601, 31, -1, -1));

        jLabel23.setText("Fecha Ingreso");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 11, -1, -1));

        jLabel24.setText("Fecha Entrega");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(609, 11, -1, -1));

        lDEsferico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lDEsfericoActionPerformed(evt);
            }
        });
        add(lDEsferico, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 59, -1));

        lIEsferico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lIEsfericoActionPerformed(evt);
            }
        });
        add(lIEsferico, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 59, -1));

        lICilindrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lICilindricoActionPerformed(evt);
            }
        });
        add(lICilindrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 59, -1));

        lIEje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lIEjeActionPerformed(evt);
            }
        });
        add(lIEje, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 59, -1));

        lDEje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lDEjeActionPerformed(evt);
            }
        });
        add(lDEje, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 59, -1));

        lDCilindrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lDCilindricoActionPerformed(evt);
            }
        });
        add(lDCilindrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 59, -1));

        jLabel25.setText("Esferico");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, -1, -1));

        jLabel26.setText("Cilindrico");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));

        jLabel27.setText("Eje");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jLabel28.setText("D");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        jLabel35.setText("I");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, -1, -1));

        cercaLejos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lejos", "Cerca" }));
        add(cercaLejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        cDEsferico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDEsfericoActionPerformed(evt);
            }
        });
        add(cDEsferico, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 59, -1));

        cIEsferico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cIEsfericoActionPerformed(evt);
            }
        });
        add(cIEsferico, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 59, -1));

        cICilindrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cICilindricoActionPerformed(evt);
            }
        });
        add(cICilindrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 59, -1));

        cIEje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cIEjeActionPerformed(evt);
            }
        });
        add(cIEje, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 59, -1));

        cDCilindrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDCilindricoActionPerformed(evt);
            }
        });
        add(cDCilindrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 59, -1));

        cDEje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cDEjeActionPerformed(evt);
            }
        });
        add(cDEje, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, 59, -1));

        jLabel36.setText("D");
        add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, -1, -1));

        jLabel37.setText("I");
        add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        jLabel38.setText("Lejos");
        add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        jLabel39.setText("Cerca");
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, -1, -1));

        jLabel40.setText("Hora Entrega");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 58, -1, -1));

        l_dos_puntos.setText(":");
        add(l_dos_puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(632, 86, -1, -1));

        minuto_ini.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        minuto_ini.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                minuto_iniItemStateChanged(evt);
            }
        });
        add(minuto_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 83, -1, -1));

        hora_ini.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        add(hora_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 83, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    public void validaPedidoYGuardar(){
        if(validarPedido()){
            guardarPedido();
        }else{
            System.out.println("no paso validacion");
        }
    }
    private boolean validarPedido(){
        boolean validacion=true;
        validarHora();
        //
        return validacion;
    }
    public void validarHora(){
        hora=new Time((int)hora_ini.getSelectedItem(),(int)minuto_ini.getSelectedItem(), 00);
       
    }
    private void guardarPedido(){
       Usuario usuario=new Usuario("juankiss", "juankiss", "conectado:D");
       Persona persona =new Persona(nombre_cliente.getText(), apellido_cliente.getText(), telefono.getText());
       persona.guardar_en_BD();
       
       
       int total=Integer.parseInt(total_a_pagar.getText());
       int acu= Integer.parseInt(a_cuenta.getText());
       int desc=Integer.parseInt(descuento.getText());
       
       Pedido pedido= new Pedido(fecha_ingreso.getDate(), fecha_entrega.getDate(),hora, lDEsferico.getText()
                                , lDCilindrico.getText(),lDEje.getText(), lIEsferico.getText(),lICilindrico.getText()
                                , lIEje.getText(),cDEsferico.getText(), cDCilindrico.getText(),cDEje.getText()
                                , cIEsferico.getText(),cICilindrico.getText(),cIEje.getText(), audicion.getText()
                                , altura.getText(), d_p_lejos.getText(),d_p_cerca.getText(), observaciones.getText()
                                , "estado",doctor.getText(),usuario.get_id(),persona.getId());
       pedido.guardarEnBD();
       
       Pago pago= new Pago(total,"01",acu ,desc,pedido.getId()); 
       pago.guardar_en_BD();
       Lente lente=new Lente(material_lente.getText(),tipo_lente.getText(),
                             color_lente.getText(), vision_lente.getText(),"01",pedido.getId());
       lente.guardar_en_BD();
       Montura montura_a=new Montura(marca_montura.getText(), codigo_montura.getText(),
                                    color_montura.getText(),tipo_montura.getText(),
                                     tamanio_montura.getText(),"01",pedido.getId());
       montura_a.guardar_en_BD();
     }
    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_telefonoKeyTyped

    private void total_a_pagarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_a_pagarKeyTyped
       
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_total_a_pagarKeyTyped

    private void a_cuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_cuentaKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_a_cuentaKeyTyped

    private void saldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saldoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_saldoKeyTyped

    private void total_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_2KeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_total_2KeyTyped

    private void descuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descuentoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_descuentoKeyTyped

    private void lenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lenteKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_lenteKeyTyped

    private void armazonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_armazonKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_armazonKeyTyped

    private void consultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultaKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_consultaKeyTyped

    private void fecha_ingresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fecha_ingresoKeyTyped
        fecha_entrega.setMinSelectableDate(fecha_ingreso.getDate());
    }//GEN-LAST:event_fecha_ingresoKeyTyped

    private void fecha_ingresoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fecha_ingresoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_fecha_ingresoAncestorAdded

    private void tamanio_monturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tamanio_monturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tamanio_monturaActionPerformed

    private void material_lenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_material_lenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_material_lenteActionPerformed

    private void tipo_lenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipo_lenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipo_lenteActionPerformed

    private void color_lenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color_lenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_color_lenteActionPerformed

    private void vision_lenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vision_lenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vision_lenteActionPerformed

    private void lDEsfericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lDEsfericoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lDEsfericoActionPerformed

    private void lIEsfericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lIEsfericoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lIEsfericoActionPerformed

    private void lICilindricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lICilindricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lICilindricoActionPerformed

    private void lIEjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lIEjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lIEjeActionPerformed

    private void lDEjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lDEjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lDEjeActionPerformed

    private void lDCilindricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lDCilindricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lDCilindricoActionPerformed

    private void cDEsfericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDEsfericoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDEsfericoActionPerformed

    private void cIEsfericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cIEsfericoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cIEsfericoActionPerformed

    private void cICilindricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cICilindricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cICilindricoActionPerformed

    private void cIEjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cIEjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cIEjeActionPerformed

    private void cDCilindricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDCilindricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDCilindricoActionPerformed

    private void cDEjeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cDEjeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cDEjeActionPerformed

    private void lenteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lenteKeyReleased
        if(!lente.getText().equals(""))
            calcularTotalAPagar();
    }//GEN-LAST:event_lenteKeyReleased

    private void armazonKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_armazonKeyReleased
        if(!armazon.getText().equals(""))
            calcularTotalAPagar();
    }//GEN-LAST:event_armazonKeyReleased

    private void consultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultaKeyReleased
        if(!consulta.getText().equals(""))
            calcularTotalAPagar();
    }//GEN-LAST:event_consultaKeyReleased

    private void descuentoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descuentoKeyReleased
        if(!descuento.getText().equals(""))
            calcularTotalAPagar();    
    }//GEN-LAST:event_descuentoKeyReleased

    private void a_cuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_cuentaKeyReleased
        if(!a_cuenta.getText().equals(""))
            saldo.setText(""+(Integer.parseInt(total_2.getText())-Integer.parseInt(a_cuenta.getText())));   
    }//GEN-LAST:event_a_cuentaKeyReleased

    private void minuto_iniItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_minuto_iniItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_minuto_iniItemStateChanged

    private void armazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_armazonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_armazonActionPerformed
    private void calcularTotalAPagar()
    {
        total_2.setText(""+(Integer.parseInt(lente.getText())+Integer.parseInt(armazon.getText())+Integer.parseInt(consulta.getText())+Integer.parseInt(armazon.getText())-Integer.parseInt(descuento.getText())));
        total_a_pagar.setText(total_2.getText());        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_cuenta;
    private javax.swing.JTextField altura;
    private javax.swing.JTextField apellido_cliente;
    private javax.swing.JTextField armazon;
    private javax.swing.JTextField audicion;
    private javax.swing.JTextField cDCilindrico;
    private javax.swing.JTextField cDEje;
    private javax.swing.JTextField cDEsferico;
    private javax.swing.JTextField cICilindrico;
    private javax.swing.JTextField cIEje;
    private javax.swing.JTextField cIEsferico;
    private javax.swing.JComboBox cercaLejos;
    private javax.swing.JTextField codigo_montura;
    private javax.swing.JTextField color_lente;
    private javax.swing.JTextField color_montura;
    private javax.swing.JTextField consulta;
    private javax.swing.JTextField d_p_cerca;
    private javax.swing.JTextField d_p_lejos;
    private javax.swing.JTextField descuento;
    private javax.swing.JTextField doctor;
    private com.toedter.calendar.JDateChooser fecha_entrega;
    private com.toedter.calendar.JDateChooser fecha_ingreso;
    private javax.swing.JComboBox hora_ini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lDCilindrico;
    private javax.swing.JTextField lDEje;
    private javax.swing.JTextField lDEsferico;
    private javax.swing.JTextField lICilindrico;
    private javax.swing.JTextField lIEje;
    private javax.swing.JTextField lIEsferico;
    private javax.swing.JLabel l_dos_puntos;
    private javax.swing.JTextField lente;
    private javax.swing.JTextField marca_montura;
    private javax.swing.JTextField material_lente;
    private javax.swing.JComboBox minuto_ini;
    private javax.swing.JTextField nombre_cliente;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JTextField saldo;
    private javax.swing.JTextField tamanio_montura;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField tipo_lente;
    private javax.swing.JTextField tipo_montura;
    private javax.swing.JTextField total_2;
    private javax.swing.JTextField total_a_pagar;
    private javax.swing.JTextField vision_lente;
    // End of variables declaration//GEN-END:variables
}
