/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * pedido.java
 *
 * Created on 10-jul-2013, 8:06:50
 */
package vista;

import java.sql.Time;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import objetos.Lente;
import objetos.Montura;
import objetos.Pago;
import objetos.Pedido;
import objetos.Persona;
import objetos.Usuario;
/**
 *
 * @author juanki
 */
public class pedido extends javax.swing.JPanel {

    /** Creates new form pedido */
    private Time hora=new Time(0, 0, 0);
    private JLabel fondo=new JLabel(new ImageIcon("imagenes/fondo.jpg"));
    public pedido() {
       
        initComponents();
        add(fondo,new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0,1000, -1));
        System.out.println(getSize().height+" "+getSize().width);
        valoresPorDefecto();
        
    }
    public void valoresPorDefecto(){
        //fechas
        Date fechaActual=new Date();
        fecha_ingreso.setDate(fechaActual);
        fecha_entrega.setDate(fechaActual);
        fecha_ingreso.setMinSelectableDate(fechaActual);
        fecha_entrega.setMinSelectableDate(fechaActual);
        
        //Costos $$
        lente.setText("0");
        armazon.setText("0");
        consulta.setText("0");
        descuento.setText("0");
        a_cuenta.setText("0");
    
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        apellido_cliente = new javax.swing.JTextField();
        a_cuenta = new javax.swing.JTextField();
        saldo = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        total_a_pagar = new javax.swing.JTextField();
        nombre_cliente = new javax.swing.JTextField();
        doctor = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        audicion = new javax.swing.JTextField();
        altura = new javax.swing.JTextField();
        d_p_lejos = new javax.swing.JTextField();
        d_p_cerca = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        observaciones = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        marca_montura = new javax.swing.JTextField();
        tamanio_montura = new javax.swing.JTextField();
        codigo_montura = new javax.swing.JTextField();
        color_montura = new javax.swing.JTextField();
        tipo_montura = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        material_lente = new javax.swing.JTextField();
        tipo_lente = new javax.swing.JTextField();
        color_lente = new javax.swing.JTextField();
        vision_lente = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lente = new javax.swing.JTextField();
        armazon = new javax.swing.JTextField();
        consulta = new javax.swing.JTextField();
        total_2 = new javax.swing.JTextField();
        descuento = new javax.swing.JTextField();
        fecha_ingreso = new com.toedter.calendar.JDateChooser();
        fecha_entrega = new com.toedter.calendar.JDateChooser();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lDEsferico = new javax.swing.JTextField();
        lIEsferico = new javax.swing.JTextField();
        lICilindrico = new javax.swing.JTextField();
        lIEje = new javax.swing.JTextField();
        lDEje = new javax.swing.JTextField();
        lDCilindrico = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        cercaLejos = new javax.swing.JComboBox();
        cDEsferico = new javax.swing.JTextField();
        cIEsferico = new javax.swing.JTextField();
        cICilindrico = new javax.swing.JTextField();
        cIEje = new javax.swing.JTextField();
        cDCilindrico = new javax.swing.JTextField();
        cDEje = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        l_dos_puntos = new javax.swing.JLabel();
        minuto_ini = new javax.swing.JComboBox();
        hora_ini = new javax.swing.JComboBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, -1, -1));

        jLabel2.setText("Apellidos");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        jLabel3.setText("Telefono");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jLabel4.setText("Total");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        jLabel5.setText("Acuenta");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        jLabel6.setText("Saldo");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, -1));

        jLabel7.setText("Doctor");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));
        add(apellido_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 237, -1));

        a_cuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_cuentaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                a_cuentaMouseExited(evt);
            }
        });
        a_cuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a_cuentaKeyTyped(evt);
            }
        });
        add(a_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 290, 70, -1));

        saldo.setEditable(false);
        saldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                saldoKeyTyped(evt);
            }
        });
        add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 290, 70, -1));

        telefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telefonoKeyTyped(evt);
            }
        });
        add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 85, -1));

        total_a_pagar.setEditable(false);
        total_a_pagar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                total_a_pagarKeyTyped(evt);
            }
        });
        add(total_a_pagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 70, -1));
        add(nombre_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 234, -1));
        add(doctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 241, -1));

        jLabel8.setText("AUDICION");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, -1, -1));

        jLabel9.setText("ALTURA");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, -1));

        jLabel10.setText("D. P. LEJOS");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, -1, -1));

        jLabel11.setText("D. P. CERCA");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, -1));
        add(audicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 60, -1));
        add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 62, -1));
        add(d_p_lejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 530, 56, -1));
        add(d_p_cerca, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 530, 61, -1));

        jLabel12.setText("Oservaciones");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, -1, -1));

        observaciones.setColumns(20);
        observaciones.setRows(5);
        jScrollPane1.setViewportView(observaciones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 268, 68));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MONTURA/ARMAZON", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hobo Std", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setText("Marca");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 46, -1, -1));

        jLabel30.setText("Codigo");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 72, -1, -1));

        jLabel31.setText("Color");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 98, -1, -1));

        jLabel32.setText("Tipo");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 124, -1, -1));

        jLabel33.setText("Tamaño");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 150, -1, -1));
        jPanel1.add(marca_montura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 43, 79, -1));
        jPanel1.add(tamanio_montura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 147, 79, -1));
        jPanel1.add(codigo_montura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 69, 79, -1));
        jPanel1.add(color_montura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 95, 79, -1));
        jPanel1.add(tipo_montura, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 121, 79, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 210, 180));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hobo Std", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setText("Material");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 36, -1, -1));

        jLabel15.setText("Tipo");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 65, -1, -1));

        jLabel16.setText("Color");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 87, -1, -1));

        jLabel17.setText("Vision");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 116, -1, -1));
        jPanel2.add(material_lente, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 36, 73, -1));
        jPanel2.add(tipo_lente, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 62, 73, -1));
        jPanel2.add(color_lente, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 87, 73, -1));
        jPanel2.add(vision_lente, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 113, 73, -1));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 210, 150));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PAGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Hobo Std", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setText("Lente");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel19.setText("Armazon");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel20.setText("Consulta");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 21));

        jLabel21.setText("Total");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel22.setText("Descuento");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        lente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lenteMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lenteMouseExited(evt);
            }
        });
        lente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lenteKeyTyped(evt);
            }
        });
        jPanel3.add(lente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 71, -1));

        armazon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                armazonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                armazonMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                armazonMousePressed(evt);
            }
        });
        armazon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                armazonKeyTyped(evt);
            }
        });
        jPanel3.add(armazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 71, -1));

        consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                consultaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                consultaMouseExited(evt);
            }
        });
        consulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                consultaKeyTyped(evt);
            }
        });
        jPanel3.add(consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 71, -1));

        total_2.setEditable(false);
        total_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                total_2KeyTyped(evt);
            }
        });
        jPanel3.add(total_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 71, -1));

        descuento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                descuentoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                descuentoMouseExited(evt);
            }
        });
        descuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descuentoKeyTyped(evt);
            }
        });
        jPanel3.add(descuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 72, -1));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 109, 210, 170));

        fecha_ingreso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fecha_ingreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fecha_ingresoKeyTyped(evt);
            }
        });
        add(fecha_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));
        add(fecha_entrega, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        jLabel23.setText("Fecha Ingreso");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jLabel24.setText("Fecha Entrega");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, -1, -1));
        add(lDEsferico, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 59, -1));
        add(lIEsferico, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 59, -1));
        add(lICilindrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, 59, -1));
        add(lIEje, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 59, -1));
        add(lDEje, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 59, -1));
        add(lDCilindrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, 59, -1));

        jLabel25.setText("Esferico");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        jLabel26.setText("Cilindrico");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 370, -1, -1));

        jLabel27.setText("Eje");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        jLabel28.setText("D");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, -1, -1));

        jLabel35.setText("I");
        add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, -1, -1));

        cercaLejos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lejos", "Cerca" }));
        add(cercaLejos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, -1, -1));
        add(cDEsferico, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 450, 59, -1));
        add(cIEsferico, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 480, 59, -1));
        add(cICilindrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 59, -1));
        add(cIEje, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 59, -1));
        add(cDCilindrico, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 450, 59, -1));
        add(cDEje, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 59, -1));

        jLabel36.setText("D");
        add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, -1, -1));

        jLabel37.setText("I");
        add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, -1, -1));

        jLabel38.setText("Lejos");
        add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        jLabel39.setText("Cerca");
        add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, -1, -1));

        jLabel40.setText("Hora Entrega");
        add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        l_dos_puntos.setText(":");
        add(l_dos_puntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, -1, -1));

        minuto_ini.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        add(minuto_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 140, -1, -1));

        hora_ini.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        add(hora_ini, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    public boolean validaPedidoYGuardar(){
        boolean exito=false;
        if(validarDatosCliente()&&validarPago()&&validarFechas()){
            guardarPedido();
            exito=true;
        }else{
            System.out.println("no paso validacion");
        }
        return exito;
    }
    private boolean validarFechas(){
        boolean validacion=false;
            try {
                    if(fecha_entrega.getDate().before(fecha_ingreso.getDate()))
                        JOptionPane.showMessageDialog(null, "no es posible entregar antes de la fecha de ingreso");
                    else
                        validacion=true;
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "una de las fechas ingresadas no es valida");
                }
        
        
        return validacion;
    }
    public boolean validarPago(){
        boolean validacion=false;
        if(!total_2.getText().equals(""))
            validacion=true;
        else
            JOptionPane.showMessageDialog(null, "el total no es correcto");
        return validacion;
    }
    private boolean validarDatosCliente(){
        boolean validacion=false;
        validarHora();
        if(nombre_cliente.getText().equals("")&&apellido_cliente.getText().equals("")){
            JOptionPane.showMessageDialog(null, "no coloco nombre y apellido");
        }else{
            if(nombre_cliente.getText().equals(""))
            JOptionPane.showMessageDialog(null, "no coloco nombre");
            else{
                if(apellido_cliente.getText().equals(""))
                JOptionPane.showMessageDialog(null, "no coloco apellido");
                else{
                    validacion=true;
                }
              }
            }
        return validacion;
    }
    public void validarHora(){
        int hora_=Integer.parseInt(""+hora_ini.getSelectedItem());
        int minuto=Integer.parseInt(""+minuto_ini.getSelectedItem());
        hora=new Time(hora_,minuto,0);
       
    }
    private void guardarPedido(){
       Usuario usuario=new Usuario("juankiss", "juankiss", "conectado:D");
       Persona persona =new Persona(nombre_cliente.getText(), apellido_cliente.getText(), telefono.getText());
       persona.guardar_en_BD();
       
       
       int total=Integer.parseInt(total_a_pagar.getText());
       int acu= Integer.parseInt(a_cuenta.getText());
       int desc=Integer.parseInt(descuento.getText());
       
       Pedido pedido= new Pedido(fecha_ingreso.getDate(), fecha_entrega.getDate(),hora, lDEsferico.getText()
                                , lDCilindrico.getText(),lDEje.getText(), lIEsferico.getText(),lICilindrico.getText()
                                , lIEje.getText(),cDEsferico.getText(), cDCilindrico.getText(),cDEje.getText()
                                , cIEsferico.getText(),cICilindrico.getText(),cIEje.getText(), audicion.getText()
                                , altura.getText(), d_p_lejos.getText(),d_p_cerca.getText(), observaciones.getText()
                                , "estado",doctor.getText(),persona.getId(),usuario.get_id());
       pedido.guardarEnBD();
       
       Pago pago= new Pago(total,"01",acu ,desc,pedido.getId()); 
       pago.guardar_en_BD();
       Lente lente=new Lente(material_lente.getText(),tipo_lente.getText(),
                             color_lente.getText(), vision_lente.getText(),"01",pedido.getId());
       lente.guardar_en_BD();
       Montura montura_a=new Montura(marca_montura.getText(), codigo_montura.getText(),
                                    color_montura.getText(),tipo_montura.getText(),
                                     tamanio_montura.getText(),"01",pedido.getId());
       montura_a.guardar_en_BD();
     }
    private void telefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telefonoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_telefonoKeyTyped

    private void total_a_pagarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_a_pagarKeyTyped
       
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_total_a_pagarKeyTyped

    private void a_cuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a_cuentaKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_a_cuentaKeyTyped

    private void saldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saldoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_saldoKeyTyped

    private void total_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_total_2KeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_total_2KeyTyped

    private void descuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descuentoKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_descuentoKeyTyped

    private void lenteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lenteKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_lenteKeyTyped

    private void armazonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_armazonKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_armazonKeyTyped

    private void consultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_consultaKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_consultaKeyTyped

    private void fecha_ingresoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fecha_ingresoKeyTyped
        fecha_entrega.setMinSelectableDate(fecha_ingreso.getDate());
    }//GEN-LAST:event_fecha_ingresoKeyTyped

    private void lenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lenteMouseClicked
        if(lente.getText().equals("0"))
            lente.setText("");
    }//GEN-LAST:event_lenteMouseClicked

    private void lenteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lenteMouseExited
        if(lente.getText().equals(""))
            lente.setText("0");
    }//GEN-LAST:event_lenteMouseExited

    private void armazonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_armazonMouseClicked
        if(armazon.getText().equals("0"))
            armazon.setText("");
    }//GEN-LAST:event_armazonMouseClicked

    private void armazonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_armazonMouseExited
        if(armazon.getText().equals(""))
            armazon.setText("0");
    }//GEN-LAST:event_armazonMouseExited

    private void consultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaMouseClicked
        if(consulta.getText().equals("0"))
            consulta.setText("");
    }//GEN-LAST:event_consultaMouseClicked

    private void consultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_consultaMouseExited
        if(consulta.getText().equals(""))
            consulta.setText("0");
    }//GEN-LAST:event_consultaMouseExited

    private void descuentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descuentoMouseClicked
        if(descuento.getText().equals("0"))
            descuento.setText("");
    }//GEN-LAST:event_descuentoMouseClicked

    private void descuentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_descuentoMouseExited
        if(descuento.getText().equals(""))
            descuento.setText("0");
    }//GEN-LAST:event_descuentoMouseExited

    private void a_cuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_cuentaMouseClicked
        if(a_cuenta.getText().equals("0"))
            a_cuenta.setText("");
    }//GEN-LAST:event_a_cuentaMouseClicked

    private void a_cuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_cuentaMouseExited
        if(a_cuenta.getText().equals(""))
            a_cuenta.setText("0");
    }//GEN-LAST:event_a_cuentaMouseExited

    private void armazonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_armazonMousePressed
        if(armazon.getText().equals("0"))
            armazon.setText("");
    }//GEN-LAST:event_armazonMousePressed
    private void calcularTotalAPagar()
    {
        if(lente.getText().equals(""))
             lente.setText("0");
        if(armazon.getText().equals(""))
             armazon.setText("0");
        if(consulta.getText().equals(""))
            consulta.setText("0");
        if(descuento.getText().equals("0"))
            descuento.setText("0");
        total_2.setText(Integer.toString(Integer.parseInt(lente.getText())+Integer.parseInt(armazon.getText())+Integer.parseInt(consulta.getText())-Integer.parseInt(descuento.getText())));
        total_a_pagar.setText(total_2.getText());        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a_cuenta;
    private javax.swing.JTextField altura;
    private javax.swing.JTextField apellido_cliente;
    private javax.swing.JTextField armazon;
    private javax.swing.JTextField audicion;
    private javax.swing.JTextField cDCilindrico;
    private javax.swing.JTextField cDEje;
    private javax.swing.JTextField cDEsferico;
    private javax.swing.JTextField cICilindrico;
    private javax.swing.JTextField cIEje;
    private javax.swing.JTextField cIEsferico;
    private javax.swing.JComboBox cercaLejos;
    private javax.swing.JTextField codigo_montura;
    private javax.swing.JTextField color_lente;
    private javax.swing.JTextField color_montura;
    private javax.swing.JTextField consulta;
    private javax.swing.JTextField d_p_cerca;
    private javax.swing.JTextField d_p_lejos;
    private javax.swing.JTextField descuento;
    private javax.swing.JTextField doctor;
    private com.toedter.calendar.JDateChooser fecha_entrega;
    private com.toedter.calendar.JDateChooser fecha_ingreso;
    private javax.swing.JComboBox hora_ini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lDCilindrico;
    private javax.swing.JTextField lDEje;
    private javax.swing.JTextField lDEsferico;
    private javax.swing.JTextField lICilindrico;
    private javax.swing.JTextField lIEje;
    private javax.swing.JTextField lIEsferico;
    private javax.swing.JLabel l_dos_puntos;
    private javax.swing.JTextField lente;
    private javax.swing.JTextField marca_montura;
    private javax.swing.JTextField material_lente;
    private javax.swing.JComboBox minuto_ini;
    private javax.swing.JTextField nombre_cliente;
    private javax.swing.JTextArea observaciones;
    private javax.swing.JTextField saldo;
    private javax.swing.JTextField tamanio_montura;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField tipo_lente;
    private javax.swing.JTextField tipo_montura;
    private javax.swing.JTextField total_2;
    private javax.swing.JTextField total_a_pagar;
    private javax.swing.JTextField vision_lente;
    // End of variables declaration//GEN-END:variables
}
