/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SaldarCuenta.java
 *
 * Created on 14-ago-2013, 13:11:10
 */
package vista;
import objetos.*;
/**
 *
 * @author juanki
 */
public class SaldarCuenta extends javax.swing.JDialog {

    /** Creates new form SaldarCuenta */
    private Pedido pedido;
    private Persona cliente;
    private Pago pago;
    int nuevoSaldoCuenta=0;
    public SaldarCuenta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void setPedido(Pedido pedido){
        this.pedido=pedido;
    }
    public void setCliente(Persona cliente){
        this.cliente=cliente;
    }
    public void setPago(Pago pago){
        this.pago=pago;
    }
    public void mostrarCuenta(){
        nombreCliente.setText(nombreCliente.getText()+" "+cliente.getName()+" "+cliente.getApellido());
        idPedido.setText(idPedido.getText()+" "+pedido.getId());
        saldo.setText(saldo.getText()+" "+pago.getSaldo());
        
    }
    private void calcularTotalAPagar()
    {
        
        if(!saldarCuenta.getText().equals("")){
            nuevoSaldoCuenta=pago.getSaldo()-Integer.parseInt(saldarCuenta.getText());
            nuevoSaldo.setText("Nuevo Saldo : "+nuevoSaldoCuenta);
        }
    }
     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreCliente = new javax.swing.JLabel();
        idPedido = new javax.swing.JLabel();
        saldo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nuevoSaldo = new javax.swing.JLabel();
        saldarCuenta = new javax.swing.JTextField();
        guardarCambios = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombreCliente.setText("Cliente :");

        idPedido.setText("ID Pedido :");

        saldo.setText("Saldo :");

        jLabel4.setText("Saldar cuenta :");

        nuevoSaldo.setText("Nuevo Saldo :");

        saldarCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                saldarCuentaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                saldarCuentaKeyTyped(evt);
            }
        });

        guardarCambios.setText("Guardar Cambios");
        guardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarCambiosActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("Cuenta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(nuevoSaldo)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(saldarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(nombreCliente)
                        .addComponent(saldo)
                        .addComponent(idPedido)
                        .addComponent(jLabel6))
                    .addComponent(guardarCambios))
                .addGap(49, 49, 49)
                .addComponent(cancelar)
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addComponent(nombreCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idPedido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(saldarCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nuevoSaldo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarCambios)
                    .addComponent(cancelar))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saldarCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saldarCuentaKeyTyped
        char car = evt.getKeyChar();
        if((car<'0' || car>'9')) evt.consume();
    }//GEN-LAST:event_saldarCuentaKeyTyped

    private void saldarCuentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_saldarCuentaKeyReleased
        calcularTotalAPagar();
    }//GEN-LAST:event_saldarCuentaKeyReleased

    private void guardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarCambiosActionPerformed
        pago.setSaldo(Integer.parseInt(saldarCuenta.getText()));
        pago.actualizar();
        dispose();
    }//GEN-LAST:event_guardarCambiosActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                SaldarCuenta dialog = new SaldarCuenta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar;
    private javax.swing.JButton guardarCambios;
    private javax.swing.JLabel idPedido;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nombreCliente;
    private javax.swing.JLabel nuevoSaldo;
    private javax.swing.JTextField saldarCuenta;
    private javax.swing.JLabel saldo;
    // End of variables declaration//GEN-END:variables
}
